✨ Add support for adding system intents directly eafb1fb
jovotech/jovo-model pull request #51
Opened 2021-09-20 11:20 UTC by rubenaeg

## Proposed changes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2021-09-20 11:45 UTC, aswetlow requested changes

2021-09-20 11:45 UTC, aswetlow commented on packages/jovo-model-google/src/JovoModelGoogle.ts
> +        console.log(Object.keys(data));
Please remove `console.log`

2021-09-20 12:02 UTC, rubenaeg commented on packages/jovo-model-google/src/JovoModelGoogle.ts
> +        console.log(Object.keys(data));
Oh, missed that one, thx for spotting!

2021-09-21 06:59 UTC, aswetlow approved these changes

2021-09-22 10:54 UTC, merged