feat(google): allow translatable entity synonyms
jovotech/jovo-model pull request #67
Opened 2022-03-08 16:16 UTC by timvermaercke

## Proposed changes

Let's say you have a multilingual Google Assistant app (with language `nl` as a default language, and `en`) with an app that only has 1 intent: to capture a score that a user can give.

This is the `models/nl.json` file
```json
{
  "intents": {
    "ScoreInputIntent": {
      "phrases": ["{score}", "Ik vind het {score}"],
      "entities": { "score": { "type": "ScoreType" } }
    }
  },
  "googleAssistant": {
    "custom": {
      "global": {
        "actions.intent.MAIN": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_INPUT_1": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_INPUT_2": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_INPUT_FINAL": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_MATCH_1": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_MATCH_2": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_MATCH_FINAL": { "handler": { "webhookHandler": "Jovo" } }
      },
      "types": {
        "ScoreType": {
          "synonym": {
            "entities": {
              "1": { "synonyms": ["1", "slecht"] },
              "2": { "synonyms": ["2", "middelmatig"] },
              "3": { "synonyms": ["3", "goed"] }
            },
            "matchType": "EXACT_MATCH"
          }
        }
      }
    }
  }
}

```

In the english model `models/en.json`, you would have something like this

```json
{
  "intents": {
    "ScoreInputIntent": {
      "phrases": ["{score}", "I think it's {score}"],
      "entities": { "score": { "type": "ScoreType" } }
    }
  },
  "googleAssistant": {
    "custom": {
      "global": {
        "actions.intent.MAIN": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_INPUT_1": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_INPUT_2": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_INPUT_FINAL": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_MATCH_1": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_MATCH_2": { "handler": { "webhookHandler": "Jovo" } },
        "actions.intent.NO_MATCH_FINAL": { "handler": { "webhookHandler": "Jovo" } }
      },
      "types": {
        "ScoreType": {
          "synonym": {
            "entities": {
              "1": { "synonyms": ["1", "bad"] },
              "2": { "synonyms": ["2", "mediocre"] },
              "3": { "synonyms": ["3", "good"] }
            }
          }
        }
      }
    }
  }
}
```

With the current code/setup, the `jovo build`-platform doesn't take the secondary languages into account and only generates a `build/[STAGE]/platform.googleAssistant/custom/types/ScoreType.yaml`
```yaml
"synonym":
  "entities":
    "1":
      "synonyms":
        - "1"
        - "slecht"
    "2":
      "synonyms":
        - "2"
        - "middelmatig"
    "3":
      "synonyms":
        - "3"
        - "goed"
  "matchType": "EXACT_MATCH"
```

Where we need a `build/[STAGE]/platform.googleAssistant/custom/types/en/ScoreType.yaml` as well with the translations for the English model
```yaml
"synonym":
  "entities":
    "1":
      "synonyms":
        - "1"
        - "bad"
    "2":
      "synonyms":
        - "2"
        - "mediocre"
    "3":
      "synonyms":
        - "3"
        - "good"
```

With this pull request the desired behaviour is introduced. When you then deploy the code to Actions on Google, the translations are available in the Console.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have added tests to cover my changes
- [x] All new and existing tests passed

2022-03-21 16:04 UTC, aswetlow commented
Awesome. Thank you! Will run a few tests and merge soon.

2022-03-22 14:07 UTC, aswetlow commented on packages/jovo-model-google/src/JovoModelGoogle.ts
> +          path: path,
Hey @timvermaercke 

Could you replace `path: path` with  `path`. Otherwise, `eslint` is failing https://github.com/jovotech/jovo-model/runs/5630383194?check_suite_focus=true

2022-03-22 14:11 UTC, aswetlow requested changes
Looks good to me, 
We will merge after the `path` eslint issue is fixed.

Thank you @timvermaercke

2022-03-23 06:43 UTC, timvermaercke commented
I fixed the line as requested. Thanks again!

2022-03-23 08:00 UTC, aswetlow approved these changes

2022-03-23 10:56 UTC, jankoenig approved these changes
Thanks!

2022-03-24 16:13 UTC, merged